import Nav from '@/components/nav/page'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import Footer from '@/components/footer/page'


export const metadata = {
  title: 'Earthie',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body><Nav/> {children}<Footer/></body>
    </html>
  )
}
